apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  api_url: http://34.148.63.195:5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: darbi/stage_front:0.2
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: api_url
          ports:
            - containerPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # Port on the pods
  type: LoadBalancer
# Remplacez cette adresse IP par votre adresse IP publique


