name: pipeline ci/cd environnement test pull request

on:
  pull_request:
    types:
      - opened

jobs:
  build-and-rename-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17

      - name: Install dependencies
        run: |
          pip install requests


      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Pull and retag the image latest
        run: |
          docker pull darbi/stage_app:latest
          docker tag darbi/stage_app:latest darbi/stage_app:0.3
          docker push darbi/stage_app:0.3
          
      - name: Execute the Python script
        env:    
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          python ./changetag.py
          
      - name: Build and tag new Docker image to latest
        run: docker build -t darbi/stage_app:latest .

      - name: Push Docker image
        run: docker push darbi/stage_app:latest

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: auth gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
    

      - name: reload gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials env-test-stage --region us-east1 --project elevated-apex-403206
          sed -i 's/image: darbi\/stage_app:latest/image: darbi\/stage_app:0.1/g' Flask_app.yaml
          kubectl apply -f Flask_app.yml
      
      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials env-test-stage --region us-east1 --project elevated-apex-403206
          sed -i 's/image: darbi\/stage_app:0.1/image: darbi\/stage_app:latest/g' Flask_app.yaml
          kubectl apply -f Flask_app.yml
