name: Deploy on Open Pull Request

on:
  pull_request:
    types:
      - closed
      
jobs:
  build-and-rename-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17

      - name: Install dependencies
        run: |
          pip install requests

      - name : change url
        run: | 
          sed -i 's/http:\/\/34.138.51.224:5000/http:\/\/34.148.63.195:5000/g' .env

      - name: Execute the Python script
        env:    
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          python ./changetag.py
          
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and tag new Docker image to latest
        run: docker build -t darbi/stage_front:latest .

      - name: Push Docker image
        run: docker push darbi/stage_front:latest
        
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: auth gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
    

      - name: reload gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials env-prod-stage --region us-east1 --project elevated-apex-403206
          sed -i 's/image: darbi\/stage_front:latest/image: darbi\/stage_front:0.1/g' front.yml
          kubectl apply -f front.yml
      
      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials env-prod-stage --region us-east1 --project elevated-apex-403206
          sed -i 's/image: darbi\/stage_front:0.1/image: darbi\/stage_front:latest/g' front.yml
          kubectl apply -f front.yml
